import Head from 'next/head';

export const HeadTag = ({ title }) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
        </div>
    );
};
